### PR TITLE
Fix nil rng

### PR DESCRIPTION
**Pull request by vmihailenco**
This was introduced in https://github.com/caio/go-tdigest/pull/27

### CODE REVIEW

**Comment by vmihailenco** [comment]
Please note that 2nd commit changes default random number generator because global generator really hurts performance because it uses `sync.Mutex`. That can be considered backwards incompatible, but since there is no way to change generator after tdigest is created (e.g. using tdigest.FromBytes) I think that is a much better default.

**Comment by caio** [comment]
Oof, nice catch! Thanks! We should drop these manual initializations - it can probably be done easily with a private `tdigest.newWithoutSummary` or similar that can be used in the serialization code.

RE changing the default RNG: I agree the local one is a better default, should've probably made it the default one when releasing v2; I'd like to keep this change for a major release though. I'm opening an issue to track that.

As for the particular problem of being unable to configure the digest on `tdigest.FromBytes`, how about
adding support for a variadic `tdigestOptions` just like `New`? It shouldn't break the api and probably ties nice with the `newWithoutSummary` thinger I mentioned above.

So 624518c is good, I'll pick and make a patch release with it asap (tomorrow morning most likely). The rng change I'd like to leave it for later. If you want to pick up the changes I suggested (or suggest better ones :blush:), go for it - otherwise I'll work on them soon after the patch release.

**Comment by caio** [comment]
> so I would solve this problem radically :)

Hahah fair enough!

I've released v2.2.1 including your fix and v2.3.0 on top of it including the `FromBytes` change to accept options. The "merge conflicts" warning on this PR is because the second patch (changing the default rng) won't apply anymore since code moved around.

**Comment by caio** [comment]
I think we may close this PR now, feel free to reopen it if necessary. Thanks again!

:wave:

**Pull request closed without merging**
