### PR TITLE
Forkupdate

### PR DESCRIPTION
**Pull request by ajgillis**

### CODE REVIEW

**Comment by ajgillis** [comment]
Access to the centroids is valuable for interoperating with other tdigest implementations.

**Comment by caio** [comment]
Hi, thank you very much for your contribution!

Can you elaborate a bit on why would that be a useful functionality? I can't think of a scenario that one would use libA centroids on libB. Besides they are pretty much implementation details (I could have pretty much encoded them on multiple primitive arrays instead).

I'm not really against the patch, but I fail to see its usefulness. I can see the point in being able to *merge* different implementations of t-digest, but that's where (de)serialisation would come in place.

**Comment by ajgillis** [comment]
Hello Caio,

The reason for the change is to allow interoperation with other TDigest implementations.  For example, if I have a TDigest collector written on one language, and it passes the datapoints (centroids) up to an aggregation service written in another language.

This could also be accomplished by being able read the serialized representation of your TDigest, but that breaks with any  change to serialization.  The important thing to accomplish is to communicate the data points to their destination, and having access to the centroids allows a user of your TDigest to do this.

-- Andrew

**Comment by ajgillis** [comment]
Hello Caio,

If (de)serialization is the intended means of interoperability, and you would prefer that to be the only way, then there is no need for my PR.  I had thought that the serialization was not intended for that purpose.

When I made this change, I was interoperating with certain implementations that take lists of centroids, either as protocol buffers or as JSON, and was looking for a way to provide that, without needing to provide de-serialization in front of each implementation.  Therefore direct access to centroids seems best for my purposes.

Of course, there are other ways that similar capability can be provided.  Possibly a "TDigest.Export()" function that returns a slice of centroids, or a slice of centroid interfaces.  Or, a function to get the mean and count at a specified index. I would be happy with any form the functionality might take.

Kindest regards,
Andrew


From: Gillis, Andrew
Sent: Tuesday, March 22, 2016 5:12 PM
To: 'caio/go-tdigest'
Subject: RE: [go-tdigest] Forkupdate (#6)

Hello Caio,

The reason for the change is to allow interoperation with other TDigest implementations.  For example, if I have a TDigest collector written on one language, and it passes the datapoints (centroids) up to an aggregation service written in another language.

This could also be accomplished by being able read the serialized representation of your TDigest, but that breaks with any  change to serialization.  The important thing to accomplish is to communicate the data points to their destination, and having access to the centroids allows a user of your TDigest to do this.

-- Andrew

**Comment by caio** [comment]
Hi Andrew,

I see. Thanks for clarifying!

So it looks to me like the best would be something along the lines of your suggested `TDigest.Export()` but without even giving out the implementation details of what a centroid is (I would really like to avoid exposing this because then any change in there would lead to backwards incompatible changes for no particular gain).

How about something like: `TDigest.forEachCentroid` which takes as an input a function reference that takes `mean` and `count` parameters and returns true/false wether to continue the iteration (I did something similar [here](https://github.com/caio/go-tdigest/blob/master/summary.go#L106))?

Code would look like:

```go
...
tdigest.forEachCentroid(func (mean float64, count uint64) bool {
    // Do anything you want with each centroid's information
})
...
```

What do you think? If you like it and wanna help out, feel free to implement it yourself otherwise just say the word and I'll write this up for you asap.

**Comment by ajgillis** [comment]
Closing this in preference for an iteration function.

**Pull request closed without merging**
